services:
  node:
    image: 'node:20'
    container_name: readme-8-general
    user: 'node'
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/node/app
    # ports:
    #   - 127.0.0.1:3000:3000
