services:
  readme-8.blog.postgres:
    image: postgres:14-alpine
    container_name: readme-8.blog.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - readme-8.postgres.blog:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - readme-8.blog

  readme-8.blog.pgadmin:
    image: dpage/pgadmin4
    container_name: readme-8.blog.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - readme-8.blog.postgres
    networks:
      - readme-8.blog

volumes:
  readme-8.postgres.blog:

networks:
  readme-8.blog:
      driver: bridge
